services:

  draw-io:

    image: ${DRAWIO_TAG:-jgraph/drawio:latest}
    hostname:  ${DRAWIO_HOSTNAME:-drawio}
    environment:
      PUBLIC_DNS: ${DRAWIO_URL}
    ports:
      - TZ: "${TZ}"
      - "${DRAWIO_PORT:-8080}:8080"
