services:

  oc-esbide:

    image: "${OC_ESBIDE_TAG}"
    hostname: "${OC_ESBIDE_HOSTNAME:-oc-esbide}"
    command: esb
    environment:
      TZ: ${TZ}
    ports:
      - "${OC_ESBIDE_SERVER_PORT:-9090}:9090"
      - "${OC_ESBIDE_DEBUG_PORT:-8080}:8080"
      - "${OC_ESBIDE_BUS_PORT:-6698}:6698"
    volumes:
      - oc_esbide_data:/var/opt/1C/1CE/instances/1c-enterprise-esb-with-ide
      - oc_esbide_usr1ce:/home/usr1ce

volumes:
  oc_esbide_data:
    external: true
    name: "${OC_ESBIDE_DATA_VOL:-oc_esbide_data}"
  oc_esbide_usr1ce:
    external: true
    name: "${OC_ESBIDE_USR_VOL:-oc_esbide_usr1ce}"
