services:

  portainer_agent:

    # compose
    container_name: "${POSTGRES_AGENT_NAME:-portainer_agent}"
    restart: always
  
    # main
    image: "${POSTGRES_AGENT_TAG:-portainer/agent:lts}"
    hostname: "${PORTAINER_AGENT_HOSTNAME}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: DEBUG