services:

  portainer_agent:

    # main
    networks:
      - agent_network

    # swarm
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:

    # main
    networks:
      - agent_network

    # swarm
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

# main
networks:
  agent_network:
    driver: overlay
    attachable: true
