services:

  portainer_agent:

    networks:
      - portainer_agent_network

    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:

    networks:
      - portainer_agent_network

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  portainer_agent_network:
    driver: overlay
    attachable: true
