services:

  portainer_agent:

    container_name: "${PORTAINER_AGENT_NAME:-portainer_agent}"
    restart: always
    ports:
      - "${PORTAINER_AGENT_PORT:-9001}:9001"
    volumes:
      - /:/host
    environment:
      AGENT_PORT: 9001

  portainer:

    container_name: "${PORTAINER_NAME:-portainer}"
    restart: always
