services:

  docker-registry:

    image: ${DOCKER_REGISTRY_TAG}
    hostname: ${DOCKER_REGISTRY_HOSTNAME:-docker-registry}
    environment:
      TZ:                            "${TZ}"
      REGISTRY_HTTP_TLS_CERTIFICATE: "/etc/docker/registry/certs/docker-registry.crt"
      REGISTRY_HTTP_TLS_KEY:         "/etc/docker/registry/certs/docker-registry.key"
      REGISTRY_HTTP_ADDR:            "0.0.0.0:${DOCKER_REGISTRY_PORT:-5000}"
      REGISTRY_AUTH:                 "htpasswd"
      REGISTRY_AUTH_HTPASSWD_PATH:   "/etc/docker/registry/auth/htpasswd"
      REGISTRY_AUTH_HTPASSWD_REALM:  "Registry Realm"
    ports:
      - "${DOCKER_REGISTRY_PORT:-5000}:${DOCKER_REGISTRY_PORT:-5000}"
    volumes:
      - docker_registry:/var/lib/registry
      - docker_registry_certs:/etc/docker/registry/certs

volumes:
  docker_registry:
    external: true
    name: ${DOCKER_REGISTRY_VOL:-docker_registry}
  docker_registry_certs:
    external: true
    name: ${DOCKER_CERTS_VOL:-docker_registry_certs}
