services:

  gitlab:

    image: "${GITLAB_TAG}"
    hostname: "${GITLAB_HOSTNAME:-gitlab}"
    logging:
      options:
        max-size: "${GITLAB_LOG_SIZE:-100M}"
    environment:
      TZ:                  "${TZ}"
      GITLAB_EXTERNAL_URL: "${GITLAB_EXTERNAL_URL}"
      GITLAB_SSH_PORT:     "${GITLAB_SSH_PORT}"
      GITLAB_EMAIL:        "${GITLAB_EMAIL}"
    ports:
      - "${GITLAB_SSH_PORT}:22"
      - "${GITLAB_HTTPS_PORT}:443"
    volumes:
      - gitlab_data:/var/opt/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_config:/etc/gitlab

volumes:
  gitlab_data:
    external: true
    name: ${GITLAB_DATA_VOL:-gitlab_data}
  gitlab_logs:
    external: true
    name: ${GITLAB_LOGS_VOL:-gitlab_logs}
  gitlab_config:
    external: true
    name: ${GITLAB_CONF_VOL:-gitlab_config}
